# fly.toml app configuration file generated for haxmail on 2023-05-21T14:38:46+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "haxmail"
primary_region = "ams"
processes = []

[env]

[experimental]
auto_rollback = true

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
port = 25

[[services.ports]]
port = 465

[[services.ports]]
handlers = ["tls"]
port = 587

[[services.ports]]
handlers = ["tls"]
port = 2525

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
